FROM python:3.10-slim
WORKDIR /app

# baseline packages + 3 additional packages!
RUN pip install sionna==1.2.1 tensorflow numpy matplotlib \
    pandas plotly tqdm

COPY simple_awgn.py .
CMD ["python", "simple_awgn.py"]